# Generated by Django 5.1.5 on 2025-01-21 10:05

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsList', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=539, size=49)),
            ],
            options={
                'get_latest_by': 'productsList',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.DecimalField(decimal_places=0, max_digits=5)),
                ('identity', models.DecimalField(decimal_places=0, max_digits=5)),
                ('date', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
